---
title: "guiuriera_PAC2_Upset"
author: "Guiu Riera Riera"
date: "18/4/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning=FALSE}
library(UpSetR)

library(mltools)
library(data.table)
```

# **1 Lectura del fitxer i preparació de les dades**

***Llegiu el fitxer fifa.csv i guardeu les dades en un objecte amb identificador denominat fifa. A continuació, verifiqueu el tipus de cada variable. Quines variables són de tipus numèric? Quines variables són de tipus categòric?***


```{r}
df_upset <- read.csv("contratos_por_municipio-sector-grupo_ocupacion-genero-edad-2016.csv", header = TRUE, sep = ";")
```


```{r}
df_upset$MES <- as.factor(df_upset$MES)
df_upset$NOM_PROV <- as.factor(df_upset$NOM_PROV)
df_upset$NOM_MUN <- as.factor(df_upset$NOM_MUN)
df_upset$DESC_SECTOR <- as.factor(df_upset$DESC_SECTOR)
df_upset$DESC_GENERO <- as.factor(df_upset$DESC_GENERO)

df_upset <- one_hot(as.data.table(df_upset))
```

```{r}
df_upset <- df_upset[,-c(1, 12, 16, 557, 562, 563, 564, 567, 568)]

head(df_upset)
```



```{r fig.width=20}
upset(df_upset, nsets = 10, number.angles = 30, point.size = 3.5, line.size = 2, 
      mainbar.y.label = "Intersecció de Contractes", sets.x.label = "Contractes per Categoria", 
      text.scale = c(2, 1.3, 1.7, 1, 2, 1.5), order.by = "freq")
```
















